apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vue-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-demo-app
      tier: frontend
  template:
    metadata:
      labels:
        app: vue-demo-app
        tier: frontend
    spec:
      containers:
        - name: vue-frontend-demo-app
          image: "jkdc/vue-demo-app:latest"
          ports:
            - containerPort: 80
            # Next will be used for https
            # - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: vue-frontend
spec:
  ports:
    - port: 4200
      protocol: TCP
      targetPort: 80
      nodePort: 32401
  selector: 
    app: vue-demo-app
    tier: frontend
  type: NodePort