apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pgweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgweb
      tier: postgres-client
  template:
    metadata:
      labels:
        app: pgweb
        tier: postgres-client
    spec:
      containers:
        - name: pgweb
          image: "sosedoff/pgweb:0.9.12"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: pgweb
spec:
  ports:
    - port: 7000
      protocol: TCP
      targetPort: 8081
      nodePort: 31000
  selector: 
    app: pgweb
    tier: postgres-client
  type: NodePort
