apiVersion: v1
kind: Service
metadata:
  name: flask-backend
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8000
      nodePort: 31651
  selector:
    app: flask-backend
    tier: mycockroach-cockroachdb-public
  type: NodePort