apiVersion: v1
kind: Service
metadata:
  name: flask-frontend
spec:
  ports:
    - port: 4200
      protocol: TCP
      targetPort: 80
      nodePort: 32401
  selector: 
    app: flask-frontend
    tier: flask-backend
  type: NodePort